name: Ruff

on:
  push:
    paths:
      - src/**
  pull_request:

permissions:
  contents: read
  
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with:
          src: "./src"